package:
    name: neuronvisio
    version: 0.8.7.dev0

source:
    # Change to match the most recent release
    #git_tag: 0.8.7.dev0
    git_url: ../

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    entry_points: 
      - neuronvisio = neuronvisio.command_line::main_neuronvisio
      - neuronvisio-model-updater = neuronvisio.commandline::main_model_updater
    
    
requirements:
    build:
        - python
    run:
        - python
        - neuron
        - mayavi
        - traits
        - ipython
        - matplotlib
        
        